name: publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    - uses: actions/checkout@master
    - run: ./build.sh
    - uses: actions/upload-artifact@v1
      with:
        name: WITCH
        path: WITCH.pdf